import { createHash, randomUUID } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
export type FlightEventKind='intent'|'tool_call'|'tool_result'|'decision'|'checkpoint'|'error'|'recovery';
export interface FlightEvent{id:string;runId:string;seq:number;at:string;kind:FlightEventKind;actor?:string;action?:string;input?:unknown;output?:unknown;error?:string;prevHash:string;hash:string}
export interface FlightRun{version:1;runId:string;startedAt:string;events:FlightEvent[]}
function stable(v:unknown):string{if(v===undefined)return'null';if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(stable).join(',')}]`;const o=v as Record<string,unknown>;return`{${Object.keys(o).sort().map(k=>`${JSON.stringify(k)}:${stable(o[k])}`).join(',')}}`}
function digest(v:unknown){return createHash('sha256').update(stable(v)).digest('hex')}
export class FlightRecorder{readonly run:FlightRun;constructor(runId:string=randomUUID()){this.run={version:1,runId,startedAt:new Date().toISOString(),events:[]}}record(event:Omit<FlightEvent,'id'|'runId'|'seq'|'at'|'prevHash'|'hash'>):FlightEvent{const prevHash=this.run.events.at(-1)?.hash??'GENESIS';const base={id:randomUUID(),runId:this.run.runId,seq:this.run.events.length,at:new Date().toISOString(),...event,prevHash};const full={...base,hash:digest(base)} as FlightEvent;this.run.events.push(full);return full}checkpoint(action:string,output?:unknown){return this.record({kind:'checkpoint',action,output})}verify(){let prevHash='GENESIS';for(const e of this.run.events){const{hash,...base}=e;if(e.prevHash!==prevHash||digest(base)!==hash)return{ok:false,badSeq:e.seq};prevHash=hash}return{ok:true}}recoveryPlan(){const cp=[...this.run.events].reverse().find(e=>e.kind==='checkpoint');return this.run.events.filter(e=>(cp?e.seq>cp.seq:true)&&['tool_call','decision','error'].includes(e.kind))}async save(path:string){await writeFile(path,JSON.stringify(this.run,null,2))}static async load(path:string){const d=JSON.parse(await readFile(path,'utf8')) as FlightRun;const r=new FlightRecorder(d.runId);r.run.startedAt=d.startedAt;r.run.events.push(...d.events);return r}}
export function compareRuns(a:FlightRun,b:FlightRun){const differences:Array<{seq:number;a?:FlightEvent;b?:FlightEvent}>=[];for(let i=0;i<Math.max(a.events.length,b.events.length);i++){const x=a.events[i],y=b.events[i];if(!x||!y||x.kind!==y.kind||x.action!==y.action||stable(x.output)!==stable(y.output))differences.push({seq:i,a:x,b:y})}return{same:differences.length===0,differences}}
